Source Data: https://archive.ics.uci.edu/dataset/101/tic+tac+toe+endgame

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving tic-tac-toe.data to tic-tac-toe (6).data

In [ ]:
import io
import pandas as pd
df = pd.read_csv(io.BytesIO(uploaded['tic-tac-toe.data']))

In [ ]:
df

     x x.1 x.2 x.3  o o.1 x.4 o.2 o.3  positive
0    x   x   x   x  o   o   o   x   o  positive
1    x   x   x   x  o   o   o   o   x  positive
2    x   x   x   x  o   o   o   b   b  positive
3    x   x   x   x  o   o   b   o   b  positive
4    x   x   x   x  o   o   b   b   o  positive
..  ..  ..  ..  .. ..  ..  ..  ..  ..       ...
952  o   x   x   x  o   o   o   x   x  negative
953  o   x   o   x  x   o   x   o   x  negative
954  o   x   o   x  o   x   x   o   x  negative
955  o   x   o   o  x   x   x   o   x  negative
956  o   o   x   x  x   o   o   x   x  negative

[957 rows x 10 columns]

In [ ]:
df.columns=[' top-left-square','top-middle-square','top-right-square','middle-left-square','middle-middle-square','middle-right-square','bottom-left-square','bottom-middle-square','bottom-right-square','Class']
df

,top-left-square,top-middle-square,top-right-square,middle-left-square,middle-middle-square,middle-right-square,bottom-left-square,bottom-middle-square,bottom-right-square,Class
0,x,x,x,x,o,o,o,x,o,positive
1,x,x,x,x,o,o,o,o,x,positive
2,x,x,x,x,o,o,o,b,b,positive
3,x,x,x,x,o,o,b,o,b,positive
4,x,x,x,x,o,o,b,b,o,positive
...,...,...,...,...,...,...,...,...,...,...
952,o,x,x,x,o,o,o,x,x,negative
953,o,x,o,x,x,o,x,o,x,negative
954,o,x,o,x,o,x,x,o,x,negative
955,o,x,o,o,x,x,x,o,x,negative
956,o,o,x,x,x,o,o,x,x,negative

In [ ]:
df.replace('x',1,inplace=True)
df.replace('o',2,inplace=True)
df.replace('b',3,inplace=True)
df.replace('positive',1,inplace=True)
df.replace('negative',0,inplace=True)
df.head()

,top-left-square,top-middle-square,top-right-square,middle-left-square,middle-middle-square,middle-right-square,bottom-left-square,bottom-middle-square,bottom-right-square,Class
0,1,1,1,1,2,2,2,1,2,1
1,1,1,1,1,2,2,2,2,1,1
2,1,1,1,1,2,2,2,3,3,1
3,1,1,1,1,2,2,3,2,3,1
4,1,1,1,1,2,2,3,3,2,1

In [ ]:
df.isnull().sum()

 top-left-square        0
top-middle-square       0
top-right-square        0
middle-left-square      0
middle-middle-square    0
middle-right-square     0
bottom-left-square      0
bottom-middle-square    0
bottom-right-square     0
Class                   0
dtype: int64

In [ ]:
# Menetapkan fitur (X) dan target (y)
X=df.drop(["Class"],axis = 1)
y=df["Class"]

# Train-Test Splitting

## Train-Test Split 70:30

In [ ]:
from sklearn.model_selection import train_test_split

# Split data menjadi data training dan testing
X_train7,X_test7, y_train7, y_test7 = train_test_split(X,y, test_size=0.3, random_state=1)

# Prediksi dan Evaluasi Performa Model
from sklearn.linear_model import LogisticRegression

# Membuat dan melatih model Regresi Logistik
model = LogisticRegression()
model.fit(X_train7, y_train7)

# Membuat prediksi pada data testing
split73 = model.predict(X_test7)

print('Jumlah data training:', len(X_train7))
print('Jumlah data testing:', len(X_test7))

Jumlah data training: 669
Jumlah data testing: 288

## Train-Test Split 80:20

In [ ]:
from sklearn.model_selection import train_test_split

# Split data menjadi data training dan testing
X_train8,X_test8, y_train8, y_test8 = train_test_split(X,y, test_size=0.2, random_state=1)

# Prediksi dan Evaluasi Performa Model
from sklearn.linear_model import LogisticRegression

# Membuat dan melatih model Regresi Logistik
model = LogisticRegression()
model.fit(X_train8, y_train8)

# Membuat prediksi pada data testing
split82 = model.predict(X_test8)

print('Jumlah data training:', len(X_train8))
print('Jumlah data testing:', len(X_test8))

Jumlah data training: 765
Jumlah data testing: 192

## Train-Test Split 90:10

In [ ]:
from sklearn.model_selection import train_test_split

# Split data menjadi data training dan testing
X_train9,X_test9, y_train9, y_test9 = train_test_split(X,y, test_size=0.1, random_state=1)

# Prediksi dan Evaluasi Performa Model
from sklearn.linear_model import LogisticRegression

# Membuat dan melatih model Regresi Logistik
model = LogisticRegression()
model.fit(X_train9, y_train9)

# Membuat prediksi pada data testing
split91 = model.predict(X_test9)

print('Jumlah data training:', len(X_train9))
print('Jumlah data testing:', len(X_test9))

Jumlah data training: 861
Jumlah data testing: 96

In [ ]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
df73 = confusion_matrix(y_test7, split73)
print("confusion matrix split data 70:30 \n", df73)
df82 = confusion_matrix(y_test8, split82)
print("confusion matrix split data 80:20 \n", df82)
df91 = confusion_matrix(y_test9, split91)
print("confusion matrix split data 90:10 \n", df91)

confusion matrix split data 70:30
 [[ 24  80]
 [ 11 173]]
confusion matrix split data 80:20
 [[ 16  51]
 [  8 117]]
confusion matrix split data 90:10
 [[ 7 28]
 [ 6 55]]

In [ ]:
report73 = classification_report(y_test7, split73)
print("Classification Report 70:30 =\n", report73)
report82 = classification_report(y_test8, split82)
print("Classification Report 80:20 =\n", report82)
report91 = classification_report(y_test9, split91)
print("Classification Report 90:10 =\n", report91)

Classification Report 70:30 =
               precision    recall  f1-score   support

           0       0.69      0.23      0.35       104
           1       0.68      0.94      0.79       184

    accuracy                           0.68       288
   macro avg       0.68      0.59      0.57       288
weighted avg       0.68      0.68      0.63       288

Classification Report 80:20 =
               precision    recall  f1-score   support

           0       0.67      0.24      0.35        67
           1       0.70      0.94      0.80       125

    accuracy                           0.69       192
   macro avg       0.68      0.59      0.58       192
weighted avg       0.69      0.69      0.64       192

Classification Report 90:10 =
               precision    recall  f1-score   support

           0       0.54      0.20      0.29        35
           1       0.66      0.90      0.76        61

    accuracy                           0.65        96
   macro avg       0.60      0.55      0.53        96
weighted avg       0.62      0.65      0.59        96

## Interpretasi Tiap Confusion Matrix



> Dari data dan hasil di atas, menunjukkan bahwa perbandingan dapat mempengaruhi confussion matrix dan berdampak pula pada akurasi yang dihasilkan pada tiap split data. Biasanya, perbandingan yang paling sering digunakan adalah 80:20 karena memiliki pembagian yang terhitung adil untuk data testing dan data training. Namun pada kasus ini, perbandingan 70:30 memiliki nilai akurasi yang lebih tinggi dibanding lainnya.


> jika dilihat dari entri-entrinya, split data dengan perbandingan 70:30 menunjukkan bahwa split data ini lebih baik dalam memprediksi yang benar namun lebih banyak membuat kesalahan dalam memprediksi. hal tersebut dapat dilihat dari jumlah TP + TN dan FP + FN pada confusion matrix.


> Selain itu, bila dilihat dari tujuan pemodelan ini, yakni jika untuk memodelkan permainan tic-tac-toe, dimana nilai presisi lebih diutamakan untuk menghindari pilihan yang salah sasaran atau dengan kata lain digunakan untuk mendeteksi ancaman yang sebenarnya ada, maka split data dengan perbandingan 80:20 yang lebih direkomendasikan. Jadi, untuk memilih perbandingan mana yang lebih cocok digunakan, tergantung pada metrik serta tujuan yang ingin dicapai.

# Cross Validation KFold

## Shuffle = False

In [ ]:
# cross validation
from sklearn.model_selection import KFold
n_folds = 4
accuracies=[]

kf = KFold(n_splits=n_folds)

for fold, (train_indeks, test_indeks) in enumerate(kf.split(df)):

  #Mendapatkan training dan testing pada fold
  train_data = df.iloc[train_indeks]
  test_data = df.iloc[test_indeks]

  #Memisahkan target dan fitur
  X_train = train_data.drop('Class', axis=1) #fitur
  X_test = test_data.drop('Class', axis=1) #fitur
  y_train = train_data['Class'] #target
  y_test = test_data['Class'] #target

  # Membuat dan melatih model Regresi Logistik
  model = LogisticRegression()
  model.fit(X_train, y_train)

  # Membuat prediksi pada data testing
  split = model.predict(X_test)

  cm= confusion_matrix(y_test, split)
  y_pred = model.predict(X_test)

  accuracy = accuracy_score(y_test, y_pred)
  accuracies.append(accuracy)
  #Menghitung persentase target pada masing-masing fold
  print("Fold number: ", fold)
  print("Original")
  print(df['Class'].value_counts().div(len(df)).mul(100)) # proporsi data original
  print("Training")
  print(y_train.value_counts().div(len(y_train)).mul(100))
  print("Testing")
  print(y_test.value_counts().div(len(y_test)).mul(100))
  print("confusion matrix: \n", cm)
  print("-"*30)

mean_accuracy = sum(accuracies) / len(accuracies)
print(accuracies)
print(mean_accuracy)

Fold number:  0
Original
1    65.308255
0    34.691745
Name: Class, dtype: float64
Training
1    53.695955
0    46.304045
Name: Class, dtype: float64
Testing
1    100.0
Name: Class, dtype: float64
confusion matrix:
 [[  0   0]
 [207  33]]
------------------------------
Fold number:  1
Original
1    65.308255
0    34.691745
Name: Class, dtype: float64
Training
1    53.760446
0    46.239554
Name: Class, dtype: float64
Testing
1    100.0
Name: Class, dtype: float64
confusion matrix:
 [[  0   0]
 [ 84 155]]
------------------------------
Fold number:  2
Original
1    65.308255
0    34.691745
Name: Class, dtype: float64
Training
1    66.713092
0    33.286908
Name: Class, dtype: float64
Testing
1    61.087866
0    38.912134
Name: Class, dtype: float64
confusion matrix:
 [[  0  93]
 [145   1]]
------------------------------
Fold number:  3
Original
1    65.308255
0    34.691745
Name: Class, dtype: float64
Training
1    87.047354
0    12.952646
Name: Class, dtype: float64
Testing
0    100.0
Name: Class, dtype: float64
confusion matrix:
 [[  0 239]
 [  0   0]]
------------------------------
[0.1375, 0.6485355648535565, 0.0041841004184100415, 0.0]
0.1975549163179916

### Interpretasi


> dari hasil yang ada, ditunjukkan bahwa proporsi pada fold 0, 1, dan 3 tidak seimbang. observasi untuk data pengujian hanya berasal dari kelas positif saja atau negatif saja, yang ditunjukkan oleh persentase dari data testing sebesar 100% dari satu kelas. Sehingga, nilai akurasi yang didapat tergolong sangat rendah


> Berdasarkan hasil confusion matrix juga didapat bahwa nilai TN selalu 0, yang berarti model pada tiap fold sama sekali tidak dapat memprediksi kelas negatif dengan benar. prediksi yang dihasilkan oleh model pada kelas negatif menghasilkan kesalahan klasifikasi. selain itu, model secara rata-rata hanya memprediksi kelas positif saja terlepas dari benar atau salahnya prediksi.

## Shuffle = True



> Dikarenakan pembagian data test dan train yang tidak seimbang antara kelas positif dan negatif, maka dilakukan percobaan untuk mengacak data sebelum membagi menjadi 4 fold. Dengan harapan dapat membagi data test maupun data train secara merata

In [ ]:
# cross validation
from sklearn.model_selection import KFold
n_folds = 4
accuracies=[]
kf = KFold(n_splits=n_folds, shuffle=True)

for fold, (train_indeks, test_indeks) in enumerate(kf.split(df)):

  #Mendapatkan training dan testing pada fold
  train_data = df.iloc[train_indeks]
  test_data = df.iloc[test_indeks]

  #Memisahkan target dan fitur
  X_train = train_data.drop('Class', axis=1) #fitur
  X_test = test_data.drop('Class', axis=1) #fitur
  y_train = train_data['Class'] #target
  y_test = test_data['Class'] #target

  # Membuat dan melatih model Regresi Logistik
  model = LogisticRegression()
  model.fit(X_train, y_train)

  # Membuat prediksi pada data testing
  split = model.predict(X_test)

  cm= confusion_matrix(y_test, split)
  y_pred = model.predict(X_test)

  accuracy = accuracy_score(y_test, y_pred)
  accuracies.append(accuracy)

  #Menghitung persentase target pada masing-masing fold
  print("Fold number: ", fold)
  print("Original")
  print(df['Class'].value_counts().div(len(df)).mul(100)) # proporsi data original
  print("Training")
  print(y_train.value_counts().div(len(y_train)).mul(100))
  print("Testing")
  print(y_test.value_counts().div(len(y_test)).mul(100))
  print("confusion matrix: \n", cm)
  print("-"*30)

mean_accuracy = sum(accuracies) / len(accuracies)
print(accuracies)
print(mean_accuracy)

Fold number:  0
Original
1    65.308255
0    34.691745
Name: Class, dtype: float64
Training
1    65.132497
0    34.867503
Name: Class, dtype: float64
Testing
1    65.833333
0    34.166667
Name: Class, dtype: float64
confusion matrix:
 [[ 15  67]
 [  4 154]]
------------------------------
Fold number:  1
Original
1    65.308255
0    34.691745
Name: Class, dtype: float64
Training
1    66.852368
0    33.147632
Name: Class, dtype: float64
Testing
1    60.669456
0    39.330544
Name: Class, dtype: float64
confusion matrix:
 [[ 23  71]
 [  6 139]]
------------------------------
Fold number:  2
Original
1    65.308255
0    34.691745
Name: Class, dtype: float64
Training
1    65.598886
0    34.401114
Name: Class, dtype: float64
Testing
1    64.435146
0    35.564854
Name: Class, dtype: float64
confusion matrix:
 [[ 22  63]
 [ 10 144]]
------------------------------
Fold number:  3
Original
1    65.308255
0    34.691745
Name: Class, dtype: float64
Training
1    63.649025
0    36.350975
Name: Class, dtype: float64
Testing
1    70.292887
0    29.707113
Name: Class, dtype: float64
confusion matrix:
 [[ 17  54]
 [ 20 148]]
------------------------------
[0.7041666666666667, 0.6778242677824268, 0.694560669456067, 0.6903765690376569]
0.6917320432357044

### Interpretasi
Dari di atas, dapat dilihat bahwa setelah dilakukan shuffle sebelum dibagi menjadi 4 fold, tidak ada ketimpangan yang berarti antara data train dan data test. Dengan demikian, nilai akurasi yang dihasilkan dapat meningkat dan mungkin sudah dapat dikatakan relatif baik. Kendati demikian, nilai rata-rata akurasi yang dihasilkan menunjukkan bahwa model tersebut masih dapat ditingkatkan lagi dalam menggeneralisasi data yang lebih baik.